nostr:
  privateKey: 01267001b76ea0da087f9fbffd89e682ade0c6f43b206d8ad6bb2d3462813877
  relayUrls:
    - ws://localhost:10547
mcp:
  version: 0.0.0
  name: "NextBlock: BILLBOARD DVMCP"
  about: An MCP-enabled DVM for the BILLBOARD Server
  clientName: DVM MCP Bridge Client
  clientVersion: 1.0.0
  picture: https://image.nostr.build/5bf2e2eb3b858bf72c23e53ed1f41ed0f65b2c8a805eaa48dd506b7cfec4ab88.png
  website: https://github.com/joinnextblock/promo-protocol/tree/main/packages/promo-dvmcp
  servers:
    - name: "BILLBOARD: DVMCP"
      command: bun
      args:
        - run
        - src/index.ts
whitelist:
  allowedDVMs: []
